#!/usr/bin/env ruby

require 'pathname'
current_dir = Pathname.new(File.dirname(__FILE__)).realpath

puts current_dir
failed_result = []
app_dirs = [
            'website/www',
            'website/home',
            'mq_consumer',
            'traders/sales',
            'traders/order',
            'traders/home',
            'traders/admin',
            'traders/sms',
            'traders/report',
            'cdn/image-server',
            'cdn/assets',
            'operate/admin',
            'operate/business',
            'operate/cms',
            'operate/report',
            'resale/home'
           ]


app_dirs.each do |dir|
  # Dir.chdir("#{current_dir}/#{dir}")
  cmd =<<END
        cd #{current_dir}/#{dir}
        play eclipsify --deps
END
  IO.popen(cmd) { |output|
    output.each_line { |line|
      puts "#{line}"
    }
  }
end
