#!/usr/bin/env ruby

# ~ unit/GoodsUnitTest...               PASSED     0s
# ~ unit/ShopUnitTest...                PASSED     0s
# ~ unit/ShopsTest...                   PASSED     0s
# ~ function/ShopFunctionTest...        PASSED     0s
# ~ function/SupplierGoodsTest...       PASSED     2s
# ~ selenium/Shops...                   PASSED     6s
# ~ selenium/ShopsAdd...                PASSED     2s


#test_passed_regex = /^~\s+(unit|functional|function|selenium)\/\w+\.{3}\s+PASSED/
#test_failed_regex = /^~\s+(unit|functional|function|selenium)\/\w+\.{3}\s+FAILED/
test_passed_regex = /PASSED/
test_failed_regex = /FAILED/
test_error_regex = /ERROR/

require 'pathname'
current_dir = Pathname.new(File.dirname(__FILE__)).realpath

puts current_dir
failed_result = []
app_dirs = [
            'website/www',
            'website/home',
            'traders/sales',
            'traders/order',
            'traders/home',
            'traders/admin',
            'traders/sms',
            'traders/report',
            'cdn/image-server',
            'cdn/assets',
            'mq_consumer',
            'operate/report',
            'operate/admin',
            'operate/business',
            'operate/cms',
            'resale/home'
           ]


passed_hash = Hash.new(0)
failed_hash = Hash.new(0)

app_dirs.each do |dir|
  # Dir.chdir("#{current_dir}/#{dir}")
  cmd =<<END
        cd #{current_dir}/#{dir}
        play clean;
        play auto-test --deps
END
  IO.popen(cmd) { |output|
    output.each_line { |line|
      if line =~ test_passed_regex
        passed_hash[dir] += 1
      end
      if line =~ test_failed_regex or line =~ test_error_regex
        failed_hash[dir] += 1
        failed_result << "#{dir}: #{line}"
      end
      puts "#{line}"
    }
  }
end

printf("=================== %s ====================\n", "Test Report")
printf("| %-30s | PASSED | FAILED |\n", "Project")
printf("----------------------------------------------------\n")
total_passed = 0
total_failed = 0
app_dirs.each do |dir|
  total_passed += passed_hash[dir]
  total_failed += failed_hash[dir]
  printf("| %-30s | %6d | %6d |\n", dir, passed_hash[dir], failed_hash[dir])
end
printf("----------------------------------------------------\n")
printf("| %-30s | %6d | %6d |\n", "Total", total_passed, total_failed)
printf("----------------------------------------------------\n")

system "#{current_dir}/selenium-clean.sh"

unless failed_result.empty?
  puts "Test Failured!"
  failed_result.each {|line| puts "    " + line}
  exit(1)
end
