#!/usr/bin/env ruby

require 'pathname'
current_dir = Pathname.new(File.dirname(__FILE__)).realpath

puts current_dir
failed_result = []
app_dirs = [
            'website/www',
            'website/home',
            'traders/sales',
            'traders/order',
            'traders/home',
            'traders/admin',
            'cdn/image-server',
            'operate/business'
           ]


app_dirs.each do |dir|
  # Dir.chdir("#{current_dir}/#{dir}")
  cmd =<<END
        cd #{current_dir}/#{dir}
        play clean;
        play auto-test --deps
END
  IO.popen(cmd) { |output|
    output.each_line { |line|
      if line =~ /(FAILED|errors|ERROR)/
        failed_result << "#{dir}: #{line}"
      else
        puts "#{line}"
      end
    }
  }
end

unless failed_result.empty?
  puts "Test Failured!"
  failed_result.each {|line| puts "    " + line}
  exit(1)
end
