#!/bin/bash
CURR_DIR=`pwd`
function run_auto_test() {
    if [[ -d $CURR_DIR/$1 ]]; then
        echo "Runing Play on $CURR_DIR/$1 ..."
        cd $CURR_DIR/$1
        play clean 
        play auto-test --deps
        cd $CURR_DIR
    else
        echo "$CURR_DIR/$1 Not Exists!"
    fi
}

run_auto_test website/www
run_auto_test website/home
run_auto_test traders/sales
run_auto_test traders/order
run_auto_test traders/home
run_auto_test traders/admin
run_auto_test cdn/image-server

cd $CURR_DIR
