package models.cms;

public enum BlockType {
    WEBSITE_SLIDE, DAILY_SPECIAL,WEBSITE_SUPPLIER,WEBSITE_RIGHT_SLIDE,
    
    WEBSITE_1F, WEBSITE_2F, WEBSITE_3F, WEBSITE_4F, WEBSITE_5F,
    // 外链跳转页面
    JUMP_TO_OUTER
}
